deployments/goerli/docker-compose.yaml

Add deployment files for goerli

Add deployment for goerli

---

.github/workflows/tests.yml
Dockerfile

Add ci for tests + Dockerfile

---

.dockerignore

Ignore deployments for docker

---

deployments/goerli/docker-compose.yaml

Add oracle deployment + fix vhosts

Add oracle deployment + fix vhosts

---

README.md
main.go
oracle/oracle.go
oracle/oraclestate.go
oracle/oraclestate_test.go
postgres/postgres.go

* On every checkpoint (every x slots) save all oracle state into a database.
* Integrate with metabase.

Add table for validator balances

---

oracle/merklelizer.go
oracle/merklelizer_test.go
oracle/oracle.go
oracle/oraclestate.go
oracle/utils.go
oracle/utils_test.go

* Store proofs for each deposit address

Store proofs for each deposit address

---

main.go
oracle/oracle.go
oracle/oraclestate.go
postgres/postgres.go

Store pool blocks in db

---

oracle/block_bellatrix.go

* Fixes bug where the vanila reward was being zero.

Fix vanila reward being 0

---

main.go
oracle/merklelizer.go
oracle/merklelizer_test.go
oracle/oraclestate.go
postgres/postgres.go

Store raw leafs + new table

---

deployments/docker-compose.yaml

* Bump oracle version
* Open api port `7300`

Bump version + open api port

---

main.go
oracle/fetcher.go

* Remove some `log.Fatal` causing the oracle to panic.
* Now instead of panic, it retries until success.

Remove panics + retry until ok

---

deployments/docker-compose.yaml
nwaku-1:.yml

Upgrade capella

---

.gitignore
contract/operatons.go
main.go
oracle/merklelizer.go
oracle/merklelizer_test.go
oracle/oracle.go
oracle/oracle_test.go
oracle/oraclestate.go
oracle/oraclestate_test.go

Misc changes:
* Adds logic (but not uses) to dump the state into a file. So that after a restart it can be used to resume syncing the oracle.
* Updates states and states transitions, making it compliant with the spec.
* Stores more infor about proposed, missed and wrong blocks in the state (in memory)

Misc refactors and state machine changes

---

api/README.md
api/api.go
contract/operatons.go
main.go
oracle/merklelizer.go
oracle/oraclestate.go
oracle/utils.go
oracle/utils_test.go

* Add proofs api + refactor stored state

Add proofs api + refactor stored state

---

main.go
oracle/merklelizer.go
oracle/onchain.go
oracle/oracle.go
oracle/oraclestate.go

* Add time formatter to show timestamp
* Adds listening to events
* Adds fetching merkle root from contract
* Some minor refactors
* Wait until transaction is mined (validated) or error

Listen events draft + wait till mined + refactors

---

go.mod
go.sum
main.go
oracle/utils.go
oracle/utils_test.go

Improve logs adding time to latest finalized slot

Improve logs adding time to latest finalized slot

---

api/api.go
oracle/onchain.go

* Add pool statistics endpoint + merkle root

Add pool statistics endpoint + merkle root

---

api/api.go
go.mod
main.go
oracle/block.go
oracle/merklelizer_test.go
oracle/onchain.go
oracle/onchain_test.go
oracle/oracle.go
oracle/oracle_test.go
oracle/oraclestate.go
oracle/oraclestate_test.go
oracle/reconciliation.go
postgres/postgres.go

Misc refactors + logs

---

api/README.md
api/api.go
main.go
oracle/block.go
oracle/block_test.go
oracle/merklelizer.go
oracle/merklelizer_test.go
oracle/onchain.go
oracle/oracle.go
oracle/oracle_test.go
oracle/oraclestate.go
oracle/oraclestate_test.go
oracle/reconciliation.go

* Add support for donations
* Add api endpoint for donations
* Fix bug where poolAddress was being used instead of poolFeesAddress

Draft adding support for donations

---

api/api.go
config/config.go

all relayers checked are predefined in the code
closes: https://github.com/dappnode/mev-sp-oracle/issues/28

New API endpoint: /registeredrelays

---

api/api.go
main.go
oracle/onchain.go
oracle/oracle.go
oracle/oracle_test.go
oracle/oraclestate.go
oracle/oraclestate_test.go

* Major refactor to decouple fetching extarnal data from the calculations. This makes it easier to unit test the code without relying on external data sources (eg consensus and execution clients)
* Add warning after every failed attemp for onchain interactions.
* Remove some to verbose logs.

Refactors and tests to facilitate testing

---

api/README.md
api/api.go
postgres/postgres.go

* Add endpoint to get the merkle proofs to claim the pool owner fees
* Add endpoint to get the merkle proofs to claim each deposit addres balance
Note that the first can be seen as a subset of the second, but comes in handy for the pool owner to have such enpoint.

Add api endpoints to get the proofs for fee + rewards

---

oracle/oraclestate.go
oracle/oraclestate_test.go

* Fixes unsubscribe logic, by sharing the pending rewards of the unsubscribed validator.

Fix unsubscribe logic

---

api/README.md
api/api.go
config/config.go
main.go
oracle/onchain.go
oracle/oraclestate.go
oracle/utils.go
oracle/utils_test.go

* Add `/allblocks`
* Add `/config`
* Edit `/onchain/proof` including missing information.

Add more api endpoints

---

oracle/oraclestate.go
oracle/oraclestate_test.go
oracle/utils.go

Add check to subscribe only if sender matches withrawal address

Add check to subscribe only if sender matches withrawal add

---

.gitignore
config/config.go
deployments/docker-compose.yaml
oracle/onchain.go

* Use password protected keystore instead raw keys

Use keystore instead raw keys

---

api/api.go

Return timestamp in seconds

---

oracle/oraclestate.go

Dont panic on marshalling

---

deployments/monitoring/prometheus-config.yml
go.mod
go.sum
main.go
metrics/metrics.go

* Add metrics to the oracle, to report latest procesed slot, slots from latest finalized slots and latest known root/slot.

Add prometheus metrics for oracle

---

main.go
oracle/block.go
oracle/block_test.go
oracle/merklelizer.go
oracle/onchain.go
oracle/oracle.go
oracle/oraclestate.go
oracle/oraclestate_test.go

* Persist state to file only at the end, once everything went fine.
* Some refactors.
* Rely on events for donations, to also get internal tx donations (donations made via smart contracts)

Misc fixes and refactors

---

main.go
oracle/block.go
oracle/block_test.go
oracle/onchain.go
oracle/onchain_test.go
oracle/oracle.go
oracle/oraclestate.go
oracle/utils.go
oracle/utils_test.go

* Rewards were only calculated in ok proposed blocks to the pool, but not for blocks that had a wrong fee recipient.
* With this PR, blocks with a wrong fee recipient but subscribed to the pool, will get their reward calculated.

Calculate rewards in wrong fee blocks

---

api/api.go
api/types.go
oracle/oraclestate.go

* Isolate api types from oracle

Isolate api types

---

oracle/onchain.go
oracle/oracle.go

* The pool fee %, poo fee address, checkpoint sice in slots and collateral are considered static parameters.
* If there is an event changing them, panic as the feature is not implemented.
* In the future we might consider being able to change them while oracle is running.

Check params have not changes

---

.gitignore
api/api.go
api/types.go
main.go
oracle/block_test.go
oracle/onchain.go
oracle/oracle.go
oracle/oracle_test.go
oracle/types.go

* Persist state to human readable json instead of gob.
* Remove old logic related to .gob.

Persist to json instead of gob

---

config/config.go
deployments/docker-compose.yaml
main.go
oracle/oracle.go

Add log level debug + flag

---

api/api.go
api/api_test.go
api/types.go
main.go
metrics/metrics.go
oracle/block.go
oracle/oracle.go
oracle/types.go

* Adds more prometheus metrics:
* With oracle version
* With http request paths, response times and codes
* Misc refactors and remove old todos

Add metrics: version + https req times/path

---

.gitignore
README.md
main.go
oracle/onchain.go
oracle/onchain_test.go

Check address is whitelistede and has balance

Check address is whitelistede and has balance

---

api/README.md
api/api.go
config/config.go
main.go
oracle/oracle.go

Add checkpoint sync

---

config/config.go

Hide keystore password in logs

Hide keystore password in logs

---

README.md
api/api.go

Calculate next and previous checkpoint metrics in api from onchain data

Calculate next and previous checkpoint metrics in api from onchain data

---

api/api.go

Include donations in rewards calculations in api

Include donations in rewards calculations in api

---

README.md
deployments/monitoring/prometheus-config.yml

Push metrics to remote prometheus instance

Push metrics to remote prometheus instance

---

oracle/onchain.go

Comment gasTipCap since its unused

Comment gasTipCap since its unused

---

api/api.go
config/config.go

_Api service needs cliConfig now to access relayers as a field part of its `CliConfig` struct  and not an exported variable. We could avoid this by adding the relayers URLs to the oracle "cfg" object, but this would mean adding a new field to the `oracleState` struct._
This new `relayers-endpoints` flag is a mandatory flag. It takes relayers URLs separated by commas. The flag cant be emtpy or have empty values. The URL has to be a valid URL (no invalid characters, blank spaces, etc), it has to start also by https://.
Tested locally, works

Change hardcoded relays to a flag

---

oracle/oracle.go

Move debug to trace to avoid having too big logs.

Move debug to trace

---

README.md

Add License section to README.md

Add License section to README.md

---

api/api.go
constants/constants.go
main.go
oracle/onchain.go
oracle/oracle.go
utils/utils.go
utils/utils_test.go

Fix comments

---

api/README.md

* Update API docs
* Remove hardcoded IPs

Update API docs

---

README.md
TERMS_OF_SERVICE.md

Legal disclaimer

---

oracle/block.go
oracle/onchain_test.go

Consider internal txs for mev rewards, since they were currently not considered and wrongly labeled as donations.

Consider internal txs for mev rewards

---

oracle/onchain.go
oracle/onchain_test.go

Add function to get the slot of a given block

Add GetSlotByBlock function

---

main.go
oracle/onchain.go

* Runs onchain reconciliation every 3 hours
* Runs onchain reconciliation before submitting a new checkpoint to the contract
* In both cases, the oracle ensures that its assets (what it has) matches its liabilities (what it owes)
* Note that reconciliation only runs in finalized blocks. Non-archival execution clients will error with `missing trie node` if you try to get a state that is before the latest finalized block.

Add onchain reconciliation

---

api/api.go

Closes https://github.com/dappnode/mev-sp-oracle/issues/217
Description:
* Seems that in some cases the consensus client can return no error but a nil `Data`, so accessing `Data.SyncDistance` could panic.
* Fixes it by checking both if the request errored + if `Data` is nil.
* Minor impact, just in the API which doesn't crash the node.

Protect from nil access when out of sync

---

oracle/onchain.go

Needed for smoothing pool holesky initialization

Add holesky as possible chain

---

oracle/oracle.go
oracle/oracle_test.go
spec/README.md

* Fixes a minor issue when calculating the rewards. Just a minor few wei rounding.

Fix minor problem in rewards

---

main.go
oracle/oracle.go
oracle/oracle_test.go

* Refactor cleanup logic.
* Runs cleanup logic in advance state function.

Refactor cleanup logic

---

oracle/block.go

* Continuation of the problem partially fixed by https://github.com/dappnode/mev-sp-oracle/pull/230
* This PR should completely fix that issue.

Fix not triggered event
