- go.mod
- go.sum
- oracle/merklelizer.go
- oracle/merklelizer_test.go
- oracle/oraclestate.go
- oracle/utils.go
- oracle/utils_test.go
> Create merkle trees to submit onchain

- README.md
- config/config.go
- contract/operatons.go
- main.go
- oracle/merklelizer.go
- oracle/oraclestate.go
* Add dry-run mode (`dry-run` cli flag). When enabled, contract is not updated. Useful when you want to recreate the state.
> Add dry-run mode

- oracle/fetcher.go
* Adds a cache for proposal duties so intead of requesting them every slot, they are just requested on every epoch.
* This substantially accelerates the time it takes to process blocks.
> Add cache for proposal duties

- api/api.go
- config/config.go
- config/config_test.go
- go.mod
- go.sum
- main.go
- oracle/block_test.go
- oracle/onchain.go
- oracle/onchain_test.go
- oracle/oracle.go
- oracle/oracle_test.go
* Most of the interactions with the execution and consensus client were only tried once, and panic if failing.
* This PR introduces a configurable retry logic, where up to `n` times the requests is retried (with some configurable logic and backoff)
> Introduce retry logic

- api/README.md
- api/api.go
- oracle/block.go
- oracle/oraclestate.go
- oracle/oraclestate_test.go
Split the api endpoints into:
* `memory`: what the oracle know 
* `onchain`: whats stored onchain (in the merkle root)
> Add memory vs onchain api endpoints + refactors

- api/api.go
- config/config.go
- config/config_test.go
- oracle/onchain.go
- postgres/postgres.go
- postgres/postgres_test.go
* Add flag to customize the number of retries before panic for consensus, execution and postgres endpoints.
* Add retry capabilities to postgres endpoint (was missing).
> Add retry flag + retry in postgres

- oracle/block.go
- oracle/block_test.go
- oracle/onchain.go
* Donations can be confused with mev-reward if using the EtherReceived event.
* This PR stops using the event for donations.
* Donations are now calculated by checking transactions within each block.
* This doesn't detect the donations made via a smart contract, pending.
> Fix donation not confused mev-rewards

- oracle/oraclestate.go
closes https://github.com/dappnode/mev-sp-oracle/issues/54
When a validator state changes, logs now show the slot/block where it happened
(_validator Index_ = _latest slot_ in this example)
> Add "latest slot" to validator state change logs

- oracle/oracle_test.go
- oracle/oraclestate.go
2 changes:
- Fixed event type in _oraclestate.go_ when unsubscribing (ProposalMissed --> **Unsubscribe**)
- Added 100_slots_test
The new test iterates through 100 slots (can be adjusted to any desired number). For each slot, it randomly determines whether various events such as adding new subscriptions, new unsubscriptions, and donations ocurred. It also determines randomly the block type (ok, missed, or wrong fee), and the validator to propose the block.
Finally, the test checks that total client liabilities = total assets held by the oracle in gwei.
> add 100_slots_test + event fix

- api/README.md
- api/api.go
- oracle/merklelizer.go
- oracle/merklelizer_test.go
- oracle/onchain.go
- oracle/oracle_test.go
- oracle/oraclestate.go
- oracle/oraclestate_test.go
* Rename deposit to withdrawal as deposit addresses are no longer used and deprecated in favour of withdrawal.
> Rename deposit to withdrawal

- config/config.go
- main.go
- oracle/onchain.go
- oracle/onchain_test.go
- oracle/oracle_test.go
- oracle/oraclestate.go
- oracle/utils.go
* Due to a missing error check, the state was not being stored correctly when providing keys to update the contract.
* It was silently failing and not storing locally the state. This caused that when the oracle restarted, it couldnt load the old state, requiring to sync from th begining.
> fix: corrupted state when key was provided

- api/api.go
- main.go
- oracle/onchain.go
- oracle/oraclestate.go
* If an oracle loses its local state, it must use the existing onchain root to ensure it doesnt update old roots. If this happens, the oracle would be updating the contract with old roots, so it must keep track on the latest known state onchain, and only update the state once it has reached this one.
* This would be very rare to happen, but can happen if the oracle loses its local state.
* This is solved by only allowing the oracle to update the root once it has been able to reconstruct the latest existing onchain, meaning that "its on the same page".
> Dont update state if behind onchain root

- oracle/block.go
- oracle/oraclestate.go
In MevBlocks:
- Print the full values of FeeRecipient and TxHash, rather than just the first four characters.
- Rename the "To" field as "MEVFeeRecipient", since its the address that is recieving the MEV reward. Should be always the smoothing pool contract address
For logging changes in the oracle state:
- Previously, the printed slot was one behind the correct one, because it used LatestProcessedSlot.
- Update to use NextSlotToProcess (LatestProcessedSlot + 1), which reflects the slot the oracle state is changing to.
> Add small log fixes

- api/api.go
* Return string for big.int instead of numbers.
* Safer since dealing with big numbers can be error prone.
> Return string for big.int instead of numbers

- .gitignore
- api/api.go
- main.go
- oracle/onchain.go
- oracle/oracle.go
- oracle/oracle_test.go
- oracle/oraclestate.go
- oracle/oraclestate_test.go
- oracle/utils.go
* Use a read mutex so that when the oracle is interrupted and the state is stored onchain, we don't get an intermediate state of the oracle. The read mutex is locked until the whole block has been processed.
* Lock a write mutex in advatance oracle state function.
* Reuse the mutex all over the code, also in the api to prevent race conditions, which are less critical but still.
* Fix issue where the onchain validators were not deepcopied (just a reference)
* Reload validators from beacon chain more often
* Fix bug when updating merkle roots, minor mainly logs.
> Add mutex and misc changes

- oracle/oraclestate.go
- oracle/oraclestate_test.go
This PR contains a new functionality and two new tests to test it.
**Functionality:**
**Add new field on OracleState `CommitedStates map[string]OnchainState` that saves all commited states to the chain by their  merkle root.**  This change adds a lot of size to the OracleState, since each OnchainState has a copy of all the Validators and their information (including all blocks proposed by each validator), and this could be stored 1 time a day.
**Tests:**
**1:** **A test that checks the size of the OracleState when uploading the state of 2000 validators once every 3 days.** The test does the following:
- **Initializes an OracleState** instance some basic configuration values.
- Prepares 2000 validators with unique index values.
- **Subscribes all 2000 validators** with the same withdrawal …
> Store on OracleState all commited states + test ValidatorInfo size

- api/api.go
- oracle/oraclestate.go
- oracle/oraclestate_test.go
Delete ok_proposed, missed, and wrong fee blocks from validatorInfo struct, since all blocks are already stored in the oracle state. 
By deleting this, the API endpoint _"/memory/validators/{withdrawalAddress}"_ has been changed, since it returns the ValidatorInfo struct without the blocks related to each validator of that withdrawalAddress.
> delete blocks from validatorInfo

- deployments/docker-compose.yaml
- main.go
Multiple oracles are racing to update the root. Lets say we have m oracles with a quorum on n (n/m). The oracles will be racing to update the root and only n txs will go through and (m-n) will be reverted, as the new state will be consolidated. In order to avoid txs being reverted (which costs gas), we add a random sleep between 0 and 15 minutes to avoid a collision. This is not perfect, but it should be good enough. Statistically, it would be very improbable that n+1 oracles will wait the same amount of time producing a collision.
> Handle race condition multi oracle with delay

- .github/workflows/tests.yml
- api/api.go
- api/types.go
- oracle/block_test.go
- oracle/oracle.go
- oracle/oracle_test.go
- oracle/types.go
* Adds a field in the validator to indicate the type of subscription auto/manual
closes https://github.com/dappnode/mev-sp-oracle/issues/103
> Add subscription type to validator auto/manual

- main.go
- oracle/oracle.go
- oracle/oracle_test.go
- oracle/types.go
* Stores all events for trazability, both valid and invalid ones.
* Useful for debuging and also for reconciliation, to ensure that we we have matches what we owe.
* Having all events allows to do so.
* Closes https://github.com/dappnode/mev-sp-oracle/issues/152
> Store all events for trazability

- .gitignore
- deployments/docker-compose.yaml
- main.go
Used "log.SetOutput()" method of logrus to implement oracle writing to logs both through stdout and a file inside the container at /oracle-data/oracleLogs.txt.
This way, logs are persisted even when deleting the oracle container, since the "/oracle-data" folder is being bind mounted on host filesystem.
> Add logs persistency on oracle-data/oracleLogs.txt

- oracle/onchain.go
By default, now AreNodesInSync() method returns true, (synced). It returns false if execution client is syncing (!= nil) or consensus client distance from chain is more than 5 blocks. Also added logs so oracle operator knows which client is out of sync
> Refactor sync checks

- config/config.go
- oracle/onchain.go
- oracle/types.go
- utils/utils.go
* Change updater-keystore-path to updater-keystore-file.
* Breaking `updater-keystore-path` is deprecated.
> Change updater-keystore-path to updater-keystore-file

- api/api.go
- api/types.go
* Add missing metrics in api endpoint `/statistics`
* `total_rewards_sent_30days_wei`
* `rewards_per_validator_per_30days_wei`
> Add missing metrics in api

- oracle/onchain_test.go
- oracle/oracle.go
Bug:
* A validator with wrong withdrawal credentials (not BLS or ETH1) type can cause the oracle to crash.
* Fixed by handling this case without panic, warning that its wrong and leaving it empty, since there is nothing we can do.
* Most likely this wont happen in mainnet but in prater there were 2 validators not respecting this. [Example](https://prater.beaconcha.in/validator/413545#blocks)
> Handle wrong withdrawal credentials

- main.go
- oracle/oracle.go
- oracle/oracle_test.go
* The oracle calculated the checkpoints as simply slot%checkpointSize.
* Now it calculates the checkpoints as (slot-deploymentSlot)%checkpointSize
> Checkpoint calculations from deployed slot

- api/api.go
- api/types.go
In the frontend, we want to display donations too: https://github.com/dappnode/mev-sp-fe/issues/30
Added sender address to the donations API response. The sender from each donation was already stored in the oracle state, we just weren't returning it in API. 
Tested locally okay. 
`/memory/donations` before:
`/memory/donations` after:
Transaction in beaconcha.in:
https://prater.beaconcha.in/tx/0xb647b7c050625d565d8466db954fb6ee2976135ee12b82b25ac308e93fe3e1f4
> Add sender to API donations response

- oracle/oracle.go
- oracle/oracle_test.go
Description:
* Handle block proposals of validators with BLS withdrawal credentials. A rare case but now is handled properly, splitting the rewards among all validators subscribed into the pool.
* This should never happen in mainnet, since these validators (with bls credentials) are not allowed to subscribe to the pool.
> Fix bls proposals

- oracle/oracle.go
- oracle/oracle_test.go
Reverts https://github.com/dappnode/mev-sp-oracle/pull/197 and adds BLS blocks to the list of proposed blocks. A validator proposing a block with BLS credentials is not considered for an auto subscription, just as it was before. But now that block is tracked.
> Handle BLS block proposal

- main.go
- oracle/onchain.go
- oracle/onchain_test.go
- oracle/oracle.go
- oracle/oracle_test.go
- oracle/types.go
* Currently, the oracle checks the latest validator state (finalized) and uses it to decide if it can subscribe or not into the pool. For example, a slashed or exited validator can't subscribe into the pool.
* However, the oracle should not use the latest finalized state, but the state of the validator when it was subscribed. Example: If validator v subscribes to the pool at slot s, the oracle should use the state of that validator at state s and not the latest finalized one.
* This PR addresses that.
* Low impact, only problematic when syncing from scratch.
> Fetch validator state from given slot

- api/api.go
The endpoint `/memory/validators` was returning an empty `SubcriptionType` because the value was not appended to the returned struct `httpOkValidatorInfo`
> Add subscription type to "handleMemoryValidators"

- api/api.go
- api/types.go
Implemented new endpoint `/memory/validatorsbyindex/<indices>` 
The endpoint returns two arrays: 
- `found_validators`: array of validatorInfo (index,pubkey,status) of all validators found in oracle state
-  `not_found_validators`. array of index of all validators not found in oracle state
> Add new api endpoint `/memory/validatorsbyindex`

- main.go
- oracle/onchain.go
When a block contained no transactions, the node was panicking since a variable was uninitialized. This PR fixes it by initializing it, so that even if no transactions are present, its not nil but an empty slice.
> Fix nil receipts when no transactions

- api/api.go
The api and the oracle were getting the latest finalized block from two different sources. The API was using the finalized checkpoints (which is wrong and is behind the real finalized slot), and the oracle was using these correct one. This caused a problem in `oracle_sync_distance_slots` metric, because of an underflow when substracting two wrong slots. This PR fixes it.
> Fix finality slot

- main.go
- oracle/onchain.go
* Run on-chain reconciliation when possible.
* Ensures assets match liabilities.
* Note that in periods of non-finality and with non-archival EL, it won't be possible to fetch the required information. Instead of panics it just warns.
> Run onchain reconciliation when possible

- main.go
- oracle/onchain.go
- oracle/oracle.go
- oracle/oracle_test.go
- oracle/types.go
Closes https://github.com/dappnode/mev-sp-oracle/issues/227
* Every given interval, slashed and exited validators subscribed to the pool are unsubscribed, splitting their pending rewards to the rest of the validators.
> Dont distribute to validators not in status "activeOngoing"

- api/api.go
- api/types.go
* Adds new field to validator API endpoints containing the validator status in the beacon chain.
* The API no longer filters based on beacon status.
> Provide validator beacon status in api

- oracle/block.go
- oracle/onchain_test.go
* Slot [10400574](https://beaconcha.in/slot/10400574) had a MEV reward but the `EtherReceived` event was not triggered due to a self-destruct.
* This caused the reconciliation to fail. Ether arrived to the pool but it wasn't detected by the oracle.
* It also unfairly banned the validator. It sent the reward but since it wasn't detected, it was wrongly considered as having a wrong fee recipient.
* This PR temporally fixes this problem by hardcoding the mev reward for that block and the fee recipient.
> Fix mev reward due to missing event

- oracle/oracle.go
Description:
* Validators cleanup only applies to exited or subscribed validators.
* If a subscribed validators consolidates to a not subscribed one, it gets its pending. But is unsubscribed. If then thats existed, its rewards would be stucked.
> fix validaorscelanup post electra
